### ISSUE TITLE
localizations won't transfer correctly from shopware-extension.yml

### ISSUE THREAD

**Issue by BilobaIT-Schueler** [shopware/shopware-cli#499]
The shopware-extension.yml has following lines:

```
store:
    categories:
        - Sonderfunktionen
    type: extension
    automatic_bugfix_version_compatibility: true
    default_locale: de_DE
    localizations:
        - es_ES
        - fi_FI
        - fr_FR
        - it_IT
        - nb_NO
        - nl_NL
        - pl_PL
        - sv_SE
        - bg_BG
        - cs_CZ
        - pt_PT
        - hr_HR
        - tr_TR
        - da_DK
        - ru_RU
        - lv_LV
        - id_ID
        - el_GR
        - de_DE
        - en_GB
    availabilities:
        - German
        - International
    description:
        [...]
```

After pushing Store infos, the localizations are reverted to "English" "German". Manually added languages are removed.

![Image](https://github.com/user-attachments/assets/d437c82b-ff09-4d5b-82d3-b0d80228900d)
