### ISSUE TITLE
file is not allowed in the zip file when validating

### ISSUE THREAD

**Issue by LiaraAlis** [shopware/shopware-cli#510]
When running validation, it fails with the following error:
```
Running with gitlab-runner 15.5.0 (0d4137b8)
  on Docker 7esey49Q
Preparing the "docker" executor
Using Docker executor with image shopware/shopware-cli:latest ...
Pulling docker image shopware/shopware-cli:latest ...
Using docker image sha[2](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/4074#L2)56:cc3db29130943bca111c4d56660c[3](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/4074#L3)3e45e67b31f8736dacd10098854c07eb51b for shopware/shopware-cli:latest with digest shopware/shopware-cli@sha256:d77e72b20a693[4](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/4074#L4)fcb5ab7b212b6c3592f309906e4d341a36f15f4cf71dadb903 ...
Preparing environment
00:01
Running on runner-7esey49q-project-489-concurrent-0 via GIT-Repository...
Getting source from Git repository
00:03
Fetching changes...
Reinitialized existing Git repository in /builds/shopware/SheTinyMce/.git/
Checking out b7a4d446 as v2.3.4...
Removing SheTinyMce-v2.3.4.zip
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:11
Using docker image sha2[5](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/4074#L5)6:cc3db29130943bca111c4d56660c33e45e67b31f8736dacd10098854c07eb51b for shopware/shopware-cli:latest with digest shopware/shopware-cli@sha25[6](https://git.blackpoint.de/shopware/SheTinyMce/-/jobs/4074#L6):d77e72b20a6934fcb5ab7b212b6c3592f309906e4d341a36f15f4cf71dadb903 ...
$ shopware-cli extension validate .
+-------+---------------------+----------------------------------------------------------------------------+
| TYPE  |     IDENTIFIER      |                                  MESSAGE                                   |
+-------+---------------------+----------------------------------------------------------------------------+
| Error | zip.disallowed_file | file /builds/shopware/SheTinyMce/.gitignore is not allowed in the zip file |
+-------+---------------------+----------------------------------------------------------------------------+
Usage:
  shopware-cli extension validate [path] [flags]
Flags:
  -h, --help   help for validate
Global Flags:
      --config string   config file (default is $HOME/.shopware-cli.yaml)
      --verbose         show debug output
FATAL	validation failed
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

Running with GitLab CI. Config:
```yaml
validate_plugin:
    stage: test
    when: always
    only:
        - tags
        - web
    image:
        name: shopware/shopware-cli:latest
        entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    tags:
        - docker
    variables:
        GIT_DEPTH: "0"
    script:
        - shopware-cli extension validate .
```
